### PR TITLE
Added two python approaches to solve the longest common subsequence problem

### PR DESCRIPTION
**Pull request by jodahoney**

### CODE REVIEW

**Comment by jodahoney** [comment]
Quick question also, will this be labeled to count towards Hacktoberfest?

**Review by ascii5833 — APPROVED** [review]

**Comment by ascii5833** [comment]
> Quick question also, will this be labeled to count towards Hacktoberfest?

Yes, you can check your progress on the official webpage.

**Comment by jodahoney** [comment]
@pokemonChampion5833 It says on the official website that the project is not participating in Hacktoberfest so my pull request was not counted, do you know what that is or what can be done to fix it?

**Comment by ascii5833** [comment]
> @pokemonChampion5833 It says on the official website that the project is not participating in Hacktoberfest so my pull request was not counted, do you know what that is or what can be done to fix it?

Sorry for the late reply, time zone differences. I added the hacktoberfest label to the repo. Can you check your pull request status on the website again ?

**Pull request merged**
